### ISSUE TITLE
home page links are confusing

### ISSUE THREAD

**Issue by buuhsmead** [magneticio/vamp.io#10]
[documentation website]
On the home page there are two buttons. One  'Run Vamp with Docker' and one 'Run Vamp with Mesosphere'. If you click on 'Run Vamp with docker' the linked page opens with the title 'Quick start with Marathon' (url: http://vamp.io/documentation/installation/quick_start/) but was expecting 'Quickstart with Docker'. Clicking from the home page on 'Run Vamp with Mesosphere' I end up configuring a driver but not on a page called like 'Quickstart with Mesosphere'.

Would be nice to have two links in the main menu on the left side on the home page: 
(main)-> Installing Vamp -> Quickstart Docker
(main) -> Installing Vamp -> Quickstart Mesosphere

**Comment by olafmol** [comment]
agreed, tnx for reporting @buuhsmead and we will fix this asap!

**Comment by dragoslav** [comment]
It's updated in `develop` branch, together with the latest updates.
