### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp.io#118]
http://www.brokenlinkcheck.com/broken-links.php

http://vamp.io/documentation/v0.9.1/using-vamp/blueprints/
http://vamp.io/documentation/v0.9.1/using-vamp/breeds/
http://vamp.io/documentation/using-vamp/workfows
https://docs.rancher.com/rancher/v1.2/zh/api/api-keys/

**Comment by gggina** [comment]
![screen shot 2017-05-16 at 11 30 27](https://cloud.githubusercontent.com/assets/3646450/26099479/22819c76-3a2b-11e7-9e12-1cfa26c3864c.png)
