### ISSUE TITLE
remove references to logstash from all content

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp.io#136]
http://vamp.io/search/?s=logstash

with the current 093 we don't use logstash anymore. So we need to remove this and update the info accordingly (ie we're using filebeat to ship logs directly to ES)

**Comment by gggina** [comment]
How Vamp works:
- [ ] Version pages
- [ ] Events and metrics
- [ ] Architecture and components
- [ ] Routing and Load balancing
- [ ] Requirements

Install:
- [ ] DC/OS install instructions
- [ ] How to configure Vamp

Troubleshoot:
- [ ]  Version pages
- [ ] Troubleshoot full Vamp installation

Other:
- [ ] Feature list
