### ISSUE TITLE
Suggestion: Use Catalog entry to deploy Vamp stack in Rancher

### ISSUE THREAD

**Issue by stefanvangastel** [magneticio/vamp.io#20]
I would be willing to add a section about quickly deploying a Vamp stack in a Rancher environment using the [Rancher community catalog](https://github.com/rancher/community-catalog) to the [quickstart Rancher page](http://vamp.io/documentation/installation/rancher/).

If you guys think that is a good idea?

**Comment by olafmol** [comment]
@stefanvangastel that's a great idea, really appreciate it! Would that also make use of this work https://github.com/rawmind0/rancher-vamp ?

**Comment by stefanvangastel** [comment]
@olafmol [Pull request pending](https://github.com/rancher/community-catalog/pull/307)

Will start on pull request for your docs.

PS: Not using the rawmind0 image, only the ones in your current quickstart guide.

**Comment by olafmol** [comment]
tnx! Merged!
