### ISSUE TITLE
Link to Docker 1.9 actually points to Docker 1.10.1a

### ISSUE THREAD

**Issue by petervandenabeele** [magneticio/vamp.io#8]
At this moment, the link to Docker Toolbox install on page
http://vamp.io/documentation/installation/quick_start/
points to the generic installer for releases that is now at 1.10.1a

And the page claims that 1.10 needs a small change at this moment.

Possible work-around is to have the Docker 1.9 link to actually link to the latest Docker 1.9.x release
https://github.com/docker/toolbox/releases/tag/v1.9.1j
(no urgent problem for me, I happen to have Docker 1.9 installed)

**Comment by olafmol** [comment]
Hi Peter, Tnx for pointing this out, we will update this. Docker 1.10.1 introduced breaking changes so we're currently working on a update to solve this. So it's good to stay on docker 1.9 until we release this update.

**Comment by olafmol** [comment]
fixed in new site
