### ISSUE TITLE
Permalinks to headlines

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp.io#81]
For instance each headline has a link (hover over them):
http://typesafehub.github.io/ssl-config/LooseSSL.html#disabling-certificate-verification
http://doc.akka.io/docs/akka-http/current/scala/http/client-side/client-https-support.html#hostname-verification

This is very handy feature for section referencing.

**Comment by olafmol** [comment]
please also apply this to other title styles like H3

**Comment by olafmol** [comment]
also when jumping to an anchor it seems the page is shown half a page earlier, i.e. the title of the referenced anchor is not displayed on top but halfway the page

**Comment by gggina** [comment]
The incorrect alignment when jumping to in-page links relates to #101
