### ISSUE TITLE
(Question) difference to mantl.io

### ISSUE THREAD

**Issue by geoHeil** [magneticio/vamp.io#9]
What is different with your approach compared to mantl.io?

**Comment by olafmol** [comment]
@geoHeil tnx for asking! Mantl.io is aiming to be a complete microservices stack (like f.e . CapGemini Apollo, Rancher, Yelp PaaSta etc. VAMP is really focused on a specific domain, namely Canary-testing&releasing and workflows like autoscaling. VAMP could act as a programmable loadbalancing/routing and/or workflow "engine" that controls the different components of such a stack like Mantl.io, and provide higher-level features to control continuous-improvement feedback loops.

**Comment by olafmol** [comment]
added to http://vamp.io/why-use-vamp/vamp-compared-to/paas-and-container-systems/
