### ISSUE TITLE
Remove reference to vamp-docker project files

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp.io#98]
In http://vamp.io/documentation/installation/kubernetes/#deploy-etcd-elasticsearch-and-logstash there is a reference to vamp-docker/master/vamp-kubernetes/etcd.yml.
This file should be served form `vamp.io` project - `vamp-docker` is related to `katana`.
Also in section http://vamp.io/documentation/installation/kubernetes/#quickstart

**Comment by iamtew** [comment]
We need to make sure these are kept up to date whenever we're updating the files in our repositories, i.e. no manual copying of files between website and repositories.

**Comment by dragoslav** [comment]
If we change these files in vamp-docker we should update vamp.io katana page so for the next official release we know we may need to update all references/files.
